ARTIFACT_DIR = "artifact"
TRAIN_FILE_NAME = "train.csv"
TEST_FILE_NAME = "test.csv"
PIPELINE_NAME = "wafer"
FILE_NAME = "wafer_fault_detection.csv"
#DATA INGESTION CONSTANTS

DATA_INGESTION_FILE_DIR = "dataingestion"
DATA_INGESTION_FEATURE_STORE = "feature_store"
DATA_INGESTION_INGESTED_FILE_PATH = "ingested"
DATA_INGESTION_TRAIN_TEST_SPLIT_RATIO = 0.2

#DATA VALIDATION CONSTANTS